### ISSUE TITLE
rxjava版本不兼容

### ISSUE THREAD

**Issue by guangzq** [ForgetAll/LoadingDialog#1]
你的项目的rxjava版本和我的项目版本不一样

**Comment by ForgetAll** [comment]
抱歉，这个RxDialog只是作为一种示例，会出现这个错误，可能是因为我的失误造成的。我把RxJava的依赖放到Loading中去了，马上修复！

**Comment by ForgetAll** [comment]
发布了v1.0.4版本，将对RxJava和RxAndroid的依赖放到例子的build.gradle中去了。

**Comment by guangzq** [comment]
可以在应用的build.gradle中加一句
packagingOptions {
        pickFirst  'META-INF/rxjava.properties'
    }
就不会报上面的错误了
