### ISSUE TITLE
第二次.show空指针

### ISSUE THREAD

**Issue by liwenpeng12** [ForgetAll/LoadingDialog#10]
登录注册同一个界面，第二次.show空指针能不能解决啊，别close了，说出解决方法吧

**Comment by ForgetAll** [comment]
下个版本解决

**Comment by ghost** [comment]
同样的问题，速速解决啊

**Comment by ForgetAll** [comment]
> 同样的问题，速速解决啊

com.github.ForgetAll:LoadingDialog:v1.1.1
1.1.1 以后的版本都解决了，目前最新的版本是v1.1.2
以前抱歉了= =，今后会快速修复各位反馈的问题
