### ISSUE TITLE
希望增加一个不要文字的接口

### ISSUE THREAD

**Issue by halohoop** [ForgetAll/LoadingDialog#12]

**Comment by ForgetAll** [comment]
👌
今天刚好有空，安排

**Comment by ForgetAll** [comment]
我先关了这个issue了，下个版本

**Comment by ForgetAll** [comment]
v1.1.2版本，传入文字为null，都会隐藏文字的布局

**Comment by halohoop** [comment]
本来想继承方式去修改，结果发现里面的TextView是私有的，重写方法也没用了，如果能把里面的变量都变成protect的话，那就足够灵活了，可能你V1.1.2版本的时间都不用花了。哈哈。

**Comment by ForgetAll** [comment]
恩，后续更新可以考虑一下重新设计一下

**Comment by halohoop** [comment]
优秀如你～
