### ISSUE TITLE
不能判断dialog是否已关闭

### ISSUE THREAD

**Issue by charlieysx** [ForgetAll/LoadingDialog#2]
加载完后要判断等dialog关闭再做其他事
但是不知道怎么判断是否关闭

**Comment by ForgetAll** [comment]
以前我的确有想加这个来着……在自定义View内部其实是有监听这个绘制事件完成的，只不过后来我自己用的时候觉得开动画这玩意不太实用，就忘了改了……的确是我的疏忽，后续我会完善的，感谢你提出的问题。

**Comment by chenhaiming** [comment]
loadFailed 之后再show  那个Dialog就为空的了

**Comment by ForgetAll** [comment]
好几个月了= = 看的我自己都脸红了，下个版本会加入绘制完毕的监听。
