### ISSUE TITLE
compile 'com.github.ForgetAll:LoadingDialog:v1.0.4'失败

### ISSUE THREAD

**Issue by Notzuonotdied** [ForgetAll/LoadingDialog#3]
compile 'com.github.ForgetAll:LoadingDialog:v1.0.4'失败

**Comment by ForgetAll** [comment]
allprojects {
	repositories {
		...
		maven { url "https://jitpack.io" }
	}
}

最外层加了这个没有，因为我是用的jitpack，所以需要加上这个才能成功的添加依赖。抱歉最近在找工作，所以回复的晚了一些。

**Comment by ForgetAll** [comment]
如果没有别的问题我就关闭这个issue了
