### ISSUE TITLE
new

### ISSUE THREAD

**Issue by 643063150** [ForgetAll/LoadingDialog#4]
全局new一个LoadingDialog  加载失败后关闭，再次加载，ld.setLoadingText("登录中").show();会爆空指针异常

**Comment by ForgetAll** [comment]
这是正常的，无论是失败还是成功的回调，最终都会导致调用
```
dialog.dismiss();
dialog = null;
```
所以的确会报空指针。

**Comment by ForgetAll** [comment]
如果没有什么问题我就关闭这个issue了
